version: '3.4'

services:
  cachedb:
    container_name: cachedb
    restart: always    
    ports:
        - "6379:6379"

  adverts.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "RedisCacheSettings:ConnectionString=localhost:6379"
    depends_on:
      - cachedb
    ports:
      - "8000:80" 

